### ISSUE TITLE
Fix close button in validation error dialog after submitting invalid job posting

### ISSUE THREAD

**Issue by vanstee** [atlrug/atlrug4#52]
Instead of showing `times;` we need to just show an x. This is probably a one character fix by just adding a `&` to make it `&times;`

![screen shot 2014-03-30 at 10 53 28 pm](https://cloud.githubusercontent.com/assets/228734/2563495/af603566-b87f-11e3-86ea-3f54fffb7c8c.png)

**Comment by jasnow** [comment]
@vanstee - Is this still a problem?

**Comment by jasnow** [comment]
Verified on Heroku/DONE
