### ISSUE TITLE
-T14- Indent job postings in under "Current jobs" on "jobs" page

### ISSUE THREAD

**Issue by garettarrowood** [atlrug/atlrug4#65]
Starting easy.

**Comment by garettarrowood** [comment]
Done.  But link to contribute - contribhub.co - says the site does not exist.  I don't have access rights.

**Comment by jasnow** [comment]
Subject: Indent job postings in under "Current jobs" on "jobs" page.

**Comment by jasnow** [comment]
Where is your PR?

**Comment by garettarrowood** [comment]
Can't make one -

```// ☆ git push
ERROR: Permission to atlrug/atlrug4.git denied to garettarrowood.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by garettarrowood** [comment]
Had wrong workflow in my head. By bad.  Working out the setup now - that PR is evolving.
