### ISSUE TITLE
-T13- Fix bullet (bullet on separate line) on "jobs" page under "Current jobs"

### ISSUE THREAD

**Issue by garettarrowood** [atlrug/atlrug4#67]
If by fix - you mean get rid of.

**Comment by jasnow** [comment]
Similar to this: http://web.archive.org/web/20150219081813/http://www.atlrug.com/jobs

**Comment by jasnow** [comment]
Turned off houndci.com - FYI

**Comment by garettarrowood** [comment]
Cool. Thanks for the merge.
